import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author NileW
 */
public class BankAppForm extends javax.swing.JFrame{
    
       ArrayList<Account> accounts = Utility.readFile("accounts.txt"); // populating array list using utility class function
       Account currentAccount;
       
    private void createAccounts(){
        for(Account a : accounts){
            accountNumComboBox.addItem(a);
        }
    }
    /**
     * Creates new form BankAppForm
     */
    public BankAppForm() {
        initComponents();
        createAccounts();// Call method to create accounst in drop down menu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerNameTxtBox = new javax.swing.JTextField();
        openDateTxtBox = new javax.swing.JTextField();
        balanceTxtBox = new javax.swing.JTextField();
        accountNumComboBox = new javax.swing.JComboBox<>();
        depositBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        transferBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bank Application");

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account Number");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Open Date");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Balance");

        customerNameTxtBox.setEditable(false);
        customerNameTxtBox.setBackground(new java.awt.Color(102, 102, 102));
        customerNameTxtBox.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        customerNameTxtBox.setForeground(new java.awt.Color(255, 255, 255));
        customerNameTxtBox.setText("Bruce Banner");
        customerNameTxtBox.setName("customerNameTxtBox"); // NOI18N

        openDateTxtBox.setEditable(false);
        openDateTxtBox.setBackground(new java.awt.Color(102, 102, 102));
        openDateTxtBox.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        openDateTxtBox.setForeground(new java.awt.Color(255, 255, 255));
        openDateTxtBox.setText("1910/23/23");
        openDateTxtBox.setName("openDateTxtBox"); // NOI18N

        balanceTxtBox.setEditable(false);
        balanceTxtBox.setBackground(new java.awt.Color(102, 102, 102));
        balanceTxtBox.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        balanceTxtBox.setForeground(new java.awt.Color(255, 255, 255));
        balanceTxtBox.setText("12345.90");
        balanceTxtBox.setName("balanceTxtBox"); // NOI18N

        accountNumComboBox.setBackground(new java.awt.Color(102, 102, 102));
        accountNumComboBox.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        accountNumComboBox.setName("accountNumComboBox"); // NOI18N
        accountNumComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumComboBoxActionPerformed(evt);
            }
        });

        depositBtn.setBackground(new java.awt.Color(255, 255, 255));
        depositBtn.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        depositBtn.setText("Deposit");
        depositBtn.setName("depositBtn"); // NOI18N
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setBackground(new java.awt.Color(255, 255, 255));
        withdrawBtn.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        withdrawBtn.setText("Withdraw");
        withdrawBtn.setName("withdrawBtn"); // NOI18N
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        transferBtn.setBackground(new java.awt.Color(255, 255, 255));
        transferBtn.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        transferBtn.setText("Transfer");
        transferBtn.setName("transferBtn"); // NOI18N
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Col P & Nile ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openDateTxtBox)
                            .addComponent(customerNameTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(accountNumComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balanceTxtBox))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(withdrawBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(depositBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(openDateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(balanceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        customerNameTxtBox.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // everytime account num is selected the text fields are updated with the correct information
    private void accountNumComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumComboBoxActionPerformed
        currentAccount = (Account) accountNumComboBox.getSelectedItem(); // cast account
        customerNameTxtBox.setText(currentAccount.getAccountName()); //populates name txt box by calling name get method
        openDateTxtBox.setText(currentAccount.getOpenDate());
        balanceTxtBox.setText(String.valueOf(currentAccount.getAccountBalance())); // use value of function to convert double string
    }//GEN-LAST:event_accountNumComboBoxActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        String amountString = JOptionPane.showInputDialog(this, "Enter Deposit Amount:", "Deposit", JOptionPane.PLAIN_MESSAGE); //Getting string amount for deposit form user
        double amount = Double.parseDouble(amountString); // parse user inputted stirng amount to a double for deposit calculation
        
        if(amount <=0){
            JOptionPane.showMessageDialog(this,"DEPOSIT MUST BE GREATER THAN 0");
            return;
        }
        currentAccount.deposit(amount); // call deposoti calcualtion function and add amount to balance
        balanceTxtBox.setText(String.valueOf(currentAccount.getAccountBalance())); // use value of function to convert double string
        Utility.writeFile(accounts, "accounts.txt"); // save changes to file and array list
    }//GEN-LAST:event_depositBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        String withdrawAmountString = JOptionPane.showInputDialog(this, "Enter Withdraw Amount:", "Withdraw", JOptionPane.PLAIN_MESSAGE); //Getting string amount for deposit form user
        double withdrawAmount = Double.parseDouble(withdrawAmountString); // parse user inputted stirng amount to a double for withdraw calculation
        
        // testing for invalid input
        if(withdrawAmount > currentAccount.getAccountBalance()){
            JOptionPane.showMessageDialog(this,"WITHDRAW CAN NOT BE GREATER THAN BALANCE");
            return;
        }
        
        if(withdrawAmount <= 0){
            JOptionPane.showMessageDialog(this,"WITHDRAW MUST BE GREATER THAN 0");
            return;
        }
        
        currentAccount.withdraw(withdrawAmount); // call withdraw calcualtion function and add amount to balance
        balanceTxtBox.setText(String.valueOf(currentAccount.getAccountBalance())); // use value of function to convert double string
        Utility.writeFile(accounts, "accounts.txt"); // save changes to file and array list
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        
        String withdrawAmountString = JOptionPane.showInputDialog(this, "Enter Transfer Amount:", "Transfer", JOptionPane.PLAIN_MESSAGE); //Getting string amount for deposit form user
        double withdrawAmount = Double.parseDouble(withdrawAmountString); // parse user inputted stirng amount to a double for withdraw calculation
        
        // testing for invalid input
        if(withdrawAmount > currentAccount.getAccountBalance()){
            JOptionPane.showMessageDialog(this,"WITHDRAW CAN NOT BE GREATER THAN BALANCE");
            return;
        }
        if(withdrawAmount <= 0){
            JOptionPane.showMessageDialog(this,"WITHDRAW MUST BE GREATER THAN 0");
            return;
        }
        String accountNum = JOptionPane.showInputDialog(this, "Enter Account Number:", "Transfer", JOptionPane.PLAIN_MESSAGE); //Getting string account number From user
        Account transferAccount = null;// create new account object for transfer
        
        for(Account a : accounts){ // loop through array list of accounts and see what account matches. transfer account then becomes user inputted account
            if(a.toString().equals(accountNum)){
                transferAccount = a;
                break;
            }
        }
        
        if(transferAccount != null){
            currentAccount.transfer(transferAccount, withdrawAmount); // call transfer calcualtion function and add amount to balance
            balanceTxtBox.setText(String.valueOf(currentAccount.getAccountBalance())); // use value of function to convert double string
            Utility.writeFile(accounts, "accounts.txt"); // save changes to file and array list
        }
        else{
            JOptionPane.showMessageDialog(this,"ACCOUNT NUMBER NOT FOUND");
        }
    }//GEN-LAST:event_transferBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankAppForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Account> accountNumComboBox;
    private javax.swing.JTextField balanceTxtBox;
    private javax.swing.JTextField customerNameTxtBox;
    private javax.swing.JButton depositBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField openDateTxtBox;
    private javax.swing.JButton transferBtn;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
}
